import type { Project, SiteSettings } from "./types";

export const defaultSettings: SiteSettings = {
  whatsapp: "",
  email: "",
  instagram: "",
  available: true,
};

export const demoProjects: Project[] = [
  {
    id: "4d3c745a-7711-4000-8000-000000000001",
    slug: "portoferry-personal-website",
    title: "Portoferry. A little bit of me.",
    category: "Web Development",
    summary: "Rumah digital untuk karya, cerita, dan kolaborasi.",
    description: "Website yang sedang kamu kunjungi. Saya ingin satu tempat untuk memperkenalkan layanan web, IT, dan video tanpa memisahkan karya desain lainnya.\n\nDibangun dengan Next.js, dengan katalog proyek dan admin panel berbasis Supabase. Tampilan gelap, aksen biru es, dan tipografi yang memberi ruang untuk setiap karya.",
    image_url: "/images/project-portoferry.webp",
    project_url: "",
    year: 2026,
    tags: ["Next.js", "Supabase", "Portfolio"],
    published: true,
    is_concept: false,
    sort_order: 0,
    created_at: "2026-09-19T06:00:00Z",
  },
  {
    id: "4d3c745a-7711-4000-8000-000000000002",
    slug: "ruang-kopi",
    title: "Ruang Kopi, ruang untuk singgah.",
    category: "Web Development",
    summary: "Eksplorasi website kedai kopi dengan menu yang gampang ditemukan.",
    description: "Studi konsep mandiri, bukan proyek klien. Eksplorasi ini membayangkan website kedai kopi lokal dengan foto produk, daftar menu, dan tombol pemesanan yang mudah ditemukan di ponsel.\n\nFokusnya ada pada susunan informasi dan warna hangat. Nama Ruang Kopi dipakai sebagai nama fiktif untuk kebutuhan desain.",
    image_url: "/images/project-kopi.webp",
    thumbnail_crop: { x: 30, y: 50, zoom: 1.2 },
    project_url: "",
    year: 2026,
    tags: ["UI Design", "Landing Page", "Konsep"],
    published: true,
    is_concept: true,
    sort_order: 1,
    created_at: "2026-09-17T06:00:00Z",
  },
  {
    id: "4d3c745a-7711-4000-8000-000000000003",
    slug: "di-antara-jeda",
    title: "Di antara jeda.",
    category: "Video Editing",
    summary: "Studi visual untuk cerita perjalanan yang terasa dekat.",
    description: "Konsep moodboard dan cover untuk sebuah video perjalanan. Ini adalah eksplorasi arah visual, bukan video final atau pekerjaan klien.\n\nWarna hijau yang tenang, judul sederhana, dan komposisi lebar menjadi titik awal untuk menyusun ritme cerita. Video hasil editing dapat ditambahkan lewat tautan proyek di admin panel.",
    image_url: "/images/project-jeda.webp",
    project_url: "",
    year: 2026,
    tags: ["Moodboard", "Travel Film", "Konsep"],
    published: true,
    is_concept: true,
    sort_order: 2,
    created_at: "2026-09-15T06:00:00Z",
  },
  {
    id: "4d3c745a-7711-4000-8000-000000000004",
    slug: "creative-profile",
    title: "A face behind the pixels.",
    category: "Graphic Design",
    summary: "Eksplorasi poster profil dengan elemen antarmuka desain.",
    description: "Visual profil personal yang menggabungkan potret, tipografi, dan elemen dari perangkat desain. Gambar ini merupakan materi referensi yang disediakan Ferry untuk website Portoferry.\n\nKarya ditampilkan sebagai eksplorasi visual personal, tanpa klaim hubungan dengan merek yang muncul pada referensi.",
    image_url: "/images/project-profile.webp",
    project_url: "",
    year: 2026,
    tags: ["Poster", "Personal Branding"],
    published: true,
    is_concept: false,
    sort_order: 3,
    created_at: "2026-09-13T06:00:00Z",
  },
  {
    id: "4d3c745a-7711-4000-8000-000000000005",
    slug: "sistem-kerja",
    title: "Biar kerja nggak dua kali.",
    category: "IT Consulting",
    summary: "Contoh pemetaan alur kerja dan kebutuhan sistem usaha.",
    description: "Studi konsep untuk memperlihatkan bentuk hasil konsultasi IT. Alur kerja dipetakan dari pesanan masuk, pencatatan, hingga laporan agar kebutuhan sistem bisa dibahas secara konkret.\n\nIni bukan implementasi pada bisnis nyata. Pemetaan, rekomendasi alat, dan rencana penerapan akan disesuaikan dengan kondisi usaha masing-masing.",
    image_url: "/images/project-system.webp",
    project_url: "",
    year: 2026,
    tags: ["Workflow", "System Planning", "Konsep"],
    published: true,
    is_concept: true,
    sort_order: 4,
    created_at: "2026-09-11T06:00:00Z",
  },
  {
    id: "4d3c745a-7711-4000-8000-000000000006",
    slug: "asisten-ai",
    title: "AI untuk kerja sehari-hari.",
    category: "AI Consulting",
    summary: "Konsep asisten untuk merangkum dokumen dan menyusun draf.",
    description: "Studi konsep penggunaan AI untuk pekerjaan rutin, seperti merangkum dokumen dan membuat draf balasan. Batasan data, pemeriksaan manusia, dan biaya penggunaan menjadi bagian dari rancangan.\n\nTampilan ini merupakan ilustrasi, bukan produk aktif. Solusi AI tetap perlu diuji dengan kebutuhan dan kebijakan privasi bisnis yang akan menggunakannya.",
    image_url: "/images/project-ai.webp",
    project_url: "",
    year: 2026,
    tags: ["AI Workflow", "Knowledge Base", "Konsep"],
    published: true,
    is_concept: true,
    sort_order: 5,
    created_at: "2026-09-09T06:00:00Z",
  },
  {
    id: "77777777-7777-4777-8777-777777777777",
    slug: "contoh-artikel-brief-website",
    title: "Contoh artikel: menyiapkan brief website.",
    category: "Artikel",
    summary: "Tulisan contoh untuk mencoba kategori Artikel di mode demo.",
    description: "Ini adalah konten contoh untuk menguji tampilan tulisan, bukan artikel Ferry yang sudah dipublikasikan.\n\nBrief website bisa dimulai dengan tujuan, calon pembaca, dan informasi yang perlu mereka temukan. Daftar halaman dan bahan yang sudah tersedia membantu memperjelas kebutuhan.\n\nDi admin, ganti contoh ini dengan tulisanmu sendiri. Pisahkan paragraf dengan satu baris kosong agar mudah dibaca.",
    image_url: "/images/project-placeholder.svg",
    body_images: [
      {
        id: "ecb2e8c7-3418-45e7-a98c-f1d33e7f54b1",
        url: "/images/project-kopi.webp",
        alt: "Ilustrasi demo konsep website kedai kopi",
        caption: "Contoh gambar setelah paragraf pembuka, bukan proyek klien.",
        after_paragraph: 1,
      },
      {
        id: "ecb2e8c7-3418-45e7-a98c-f1d33e7f54b2",
        url: "/images/project-system.webp",
        alt: "Ilustrasi demo pemetaan alur kerja",
        caption: "Contoh gambar di antara paragraf tulisan.",
        after_paragraph: 2,
      },
      {
        id: "ecb2e8c7-3418-45e7-a98c-f1d33e7f54b3",
        url: "/images/project-ai.webp",
        alt: "Ilustrasi demo alur kerja AI",
        caption: "Gambar ketiga sebagai penutup contoh tulisan.",
        after_paragraph: 3,
      },
    ],
    project_url: "",
    year: 2026,
    tags: ["Artikel", "Brief", "Website"],
    published: true,
    is_concept: false,
    sort_order: 6,
    created_at: "2026-09-23T00:00:00Z",
  },
];
